backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master) 

# This line should *not* be indented
media_folder: "assets/images" # Media files will be stored in the repo under images/uploads 

collections: 
  - name: "pages" 
    label: "Pages" 
    folder: "_pages" 
    create: true 

    fields: 
      - name: "title" 
        label: "Title" 
        widget: "string"

      - name: "image_sets" 
        label: "Image Sets" 
        widget: "list" 
        fields: 
          - name: "image_set" 
            label: "Image Set" 
            widget: "list" 
            field: 
              name: "image" 
              label: "Image" 
              widget: "image" 

      - name: "image" 
        label: "Image" 
        widget: "image" 

        
